#configs
spring:
  h2:
    console:
      enabled: true
      path: /coreBanking
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:coreBanking;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: coreBanking
    password: 123456
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
springdoc:
  swagger-ui:
    path: /swagger-ui.html
explore:
  rabbitmq:
    exchange: exchange
    queue: queue
    routing-key: routing-key

