spring:
  datasource:
    url: jdbc:h2:mem:coreBanking;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=LEGACY
    username: coreBanking
    password: 123456
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

explore:
  rabbitmq:
    exchange: exchange
    queue: queue
    routing-key: routing-key
